title: The Art, Science, and Engineering of Programming
issn: 2473-7321
doi: 10.22152/programming-journal.org
host: https://programming-journal.org

lang: en
description: The Art, Science, and Engineering of Programming journal is a
  fully refereed, open access, free, electronic journal. It welcomes papers on
  the art of programming, broadly construed.

author:
  name: The  editors of The Art, Science, and Engineering of Programming
  email: editors@programming-journal.org

menu_categories: ["The Journal", "For Authors", "Issues"]

#baseurl: /

highlighter: rouge
markdown: kramdown

kramdown:
  input: kramdown
  hard_wrap: false
  footnote_backlink: ''

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


host: 0.0.0.0
# EOF
